name = "arttherapy-plus"
compatibility_date = "2024-12-01"

[site]
bucket = "./dist"

[env.production]
routes = [
  { pattern = "arttherapy-plus.pages.dev", custom_domain = false }
]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
